# build stage install all dependecies, this stage compile ts file to .js
FROM node:22-alpine AS build
WORKDIR /app
COPY package*.json .
RUN npm ci
COPY tsconfig.json tsconfig.json
COPY src src
RUN npm run build

# deps stage install only production dependecy
FROM node:22-alpine AS deps
WORKDIR /app
COPY package*.json .
RUN npm ci --only=production

# Distroless image, safe and lightweight
FROM gcr.io/distroless/nodejs22
WORKDIR /app
COPY --from=deps /app/node_modules node_modules
COPY --from=build /app/dist dist
ENV PORT=3000
CMD ["dist/index.js"]